---
title: "John Wise's Resume"
description: |
  Having navigated nearly 19 years of incarceration in Florida, I dedicated countless hours to introspection and self-improvement, and earning my degree. Now equipped with a strong foundation of skills, I am eager to embark on my career journey. My experiences have honed my ability to excel under pressure, and my knack for getting along with diverse groups of individuals has consistently proven valuable. While I may lack direct experience, I am confident that my unique background and unwavering commitment make me a valuable potential asset to any organization.
output:
  distill::distill_article:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Education

## Bachelor of Science in Data Science
**(Expected Graduation: December 2023)**
*Indiana University East*

  - Relevant Courses: Calculus for Data Science, Database Applications, Linear Algebra, Information Representation, Data Mining, Cloud Computing for Data Science
  - Transfer Credits: History, Philosophy, Computing, Statistics, Spanish, and more
  
  

# Professional Experience

## Researcher and Consultant (contract)
*Center for Public Opinion Research (CPOR) at Stetson University*  
*(October 2023 - Present)*

- Assist in packaging and interpreting data collected by CPOR.
- Prepare reports for sharing with higher education in prison programs in Florida.

## Intern  
*University of Utah Prison Education Project*  
*(May 2023 - August 2023)*

- Evaluated and provided feedback on the Education Justice Tracker.
- Conducted research on data regarding incarceration and explored the importance of administrative data accessibility.

## Fellow  
*Community Spring*
*(August 2021 - May 2022)*

- Helped found the Lighthouse Campaign on Affordable Housing.
- Conducted policy research, advocacy, public speaking, and community engagement.

## Inmate Teaching Assistant  
*Florida Department of Corrections*  
*(2013-2021)*

- Developed and implemented lesson plans.
- Delivered classroom lectures, graded assignments, and provided individual tutoring to GED test takers.



# Certifications
- **Data Analytics**
  *Google (Coursera)*


# Skills

<ul>
  <li><strong>Data Analysis and Statistics:</strong> Proficient in statistical analysis with a focus on behavioral sciences and statistical learning.</li>
  <li><strong>Programming and Computing:</strong> Skilled in programming languages and data structures, including database systems.</li>
  <li><strong>Communication:</strong> Strong written communication skills demonstrated through technical and creative writing.</li>
  <li><strong>Business and Economics:</strong> Solid understanding of macroeconomics, microeconomics, business administration, and marketing principles.</li>
  <li><strong>Critical Thinking:</strong> Developed critical thinking skills through philosophy and religion courses.</li>
  <li><strong>Environmental Science:</strong> Knowledgeable in environmental science and life sciences.</li>
  <li><strong>Mathematics:</strong> Strong foundation in calculus, linear algebra, trigonometry, and precalculus algebra.</li>
  <li><strong>Interpersonal Communication:</strong> Effective public speaking and interpersonal communication skills.</li>
  <li><strong>Data Management:</strong> Experience in data management and fluency in data-related concepts.</li>
  <li><strong>Research and Analysis:</strong> Exposure to research methodologies and analysis techniques.</li>
  <li><strong>Adaptability and Resilience:</strong> Successfully navigated diverse courses and institutions, showcasing adaptability.</li>
  <li><strong>Problem-Solving:</strong> Applied problem-solving skills in computing and data science.</li>
  <li><strong>Teamwork and Collaboration:</strong> Collaborative approach demonstrated in group projects and internships.</li>
</ul>


# Service

## Free to Learn Advisory Board Member
  *Santa Fe College (SF)*
  
  - Provide support and guidance to SF faculty and administrators working on the Free to Learn initiative.
  - Aim to increase public understanding of incarceration in Florida, advocate for current and formerly incarcerated individuals, and address obstacles they face in accessing education and resources for successful re-entry into the community.


References available upon request



