---
title: "On Recidiviz"
description: |
  My proposed solution
output:
  distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 3
    df_print: paged
---

Listen, Recidiviz does a ton of good work, and they are all good people.

They are on unstable ethical footing, and I feel it compromises what they are doing. Worse, there is the potential for great harm.

I'll make those arguments later other places, but I shouldn't fucking have to.

Here is what Recidiviz can do -- shit I'd be happy if the board would just openly consider it -- to get on a solid ethical footing, get me rooting for them, and still do all the good work.

1) Terminate all logistial support and anything that could be construed as a 'partnership' with a state carceral entity.
2) Initiate formal action to acquire the metadata structures of all prison systems.

I'm enough of a pragmatist I'd understand if they tried doing it in the reverse order.

Could do same work + more, on an ethical footing, and then make DEMANDS for more meaningful and substantial (data-backed!) changes.

My email is always open, if anyone is actually even looking at my site.